services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: postgres

  db-test:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: postgres

volumes:
  db_data:
